---
- name: Install MySQL
  apt:
    name: default-mysql-server
    state: present

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: "{{ ansible_host }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present
  ignore_errors: yes
