---
- name: Add Sury PHP repository
  shell: curl -sSL https://packages.sury.org/php/README.txt | bash -x

- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install PHP
  apt:
    name: "php{{ php_version }}"
    state: present

- name: Install PHP modules
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "php{{ php_version }}-mysql"
    - "libapache2-mod-php{{ php_version }}"

- name: Deploy info.php
  template:
    src: info.php.j2
    dest: /var/www/html/info.php
